"""Synthetic scenario specifications for CS-01 through CS-10."""

from __future__ import annotations

from src.mcms.scenario_support import DetectionSpec, ScenarioSpec

SCENARIOS: dict[str, ScenarioSpec] = {
    "CS-01": ScenarioSpec(
        "CS-01",
        "Insider Trading — Pre-Announcement Accumulation",
        ("agent-tm-001", "agent-cs-001"),
        "High",
        "CRITICAL",
        ("SEC Rule 10b-5", "FINRA Rule 2010", "Insider Trading Sanctions Act"),
        (
            DetectionSpec(
                "agent-tm-001",
                0.79,
                "CRITICAL",
                ("trade_pattern_001", "volume_anomaly_002"),
                ("PM_John_Doe", "Account_44521"),
                "insider_trading",
                {
                    "position_above_90_day_average_pct": 340,
                    "buy_orders_clustered_before_close": True,
                },
            ),
            DetectionSpec(
                "agent-cs-001",
                0.90,
                "CRITICAL",
                ("email_4452", "calendar_entry_892"),
                ("PM_John_Doe", "CFO_CompanyX"),
                "insider_trading",
                {"private_dinner": True, "official_channel_follow_up": False},
            ),
        ),
        3,
        (
            "SAR filing draft (FinCEN Form 111)",
            "Internal investigation report",
            "Regulatory notification draft (SEC)",
        ),
        expected_conflict_type=None,
    ),
    "CS-02": ScenarioSpec(
        "CS-02",
        "Market Manipulation — Spoofing in Futures Markets",
        ("agent-tm-001",),
        "Medium",
        "HIGH",
        ("Dodd-Frank Act Section 747", "CEA Section 4c(a)(5)", "CME Rule 575"),
        (
            DetectionSpec(
                "agent-tm-001",
                0.88,
                "HIGH",
                ("spoofing_signature_001", "cancel_burst_047"),
                ("crude_oil_desk",),
                "spoofing",
                {
                    "repetitions": 47,
                    "cancel_latency_ms": "200-500",
                    "opposite_side_execution": True,
                },
            ),
        ),
        2,
        ("CFTC referral draft", "Internal surveillance report"),
    ),
    "CS-03": ScenarioSpec(
        "CS-03",
        "Unsuitable Investment Recommendation",
        ("agent-cs-001", "agent-tm-001"),
        "High",
        "HIGH",
        ("FINRA Rule 2111", "SEC Regulation Best Interest"),
        (
            DetectionSpec(
                "agent-cs-001",
                0.89,
                "HIGH",
                ("advisor_message_001", "ips_violation_012"),
                ("Advisor_12",),
                "unsuitable_recommendation",
                {"retirement_clients": 12, "client_age_range": "68-82", "leveraged_etf": True},
            ),
            DetectionSpec(
                "agent-tm-001",
                0.75,
                "MEDIUM",
                ("trade_confirmations_012", "aum_risk_002"),
                ("Advisor_12",),
                "unsuitable_recommendation",
                {"aum_at_risk_usd": 2300000, "clients_executed": 12},
            ),
        ),
        2,
        ("FINRA referral", "Client remediation plan", "Advisor disciplinary report"),
        use_conflict_resolver=True,
        expected_conflict_type="B",
    ),
    "CS-04": ScenarioSpec(
        "CS-04",
        "AML — Structuring Deposits",
        ("agent-tm-001",),
        "Medium",
        "CRITICAL",
        ("Bank Secrecy Act", "31 CFR 1020.320", "FinCEN SAR"),
        (
            DetectionSpec(
                "agent-tm-001",
                0.95,
                "CRITICAL",
                ("structuring_pattern_023", "branch_spread_007"),
                ("Depositor_004",),
                "aml_structuring",
                {
                    "deposit_count": 23,
                    "branch_count": 7,
                    "total_usd": 214000,
                    "amount_range_usd": "8500-9900",
                },
            ),
        ),
        3,
        ("SAR draft (FinCEN Form 111)", "Branch alert notification"),
    ),
    "CS-05": ScenarioSpec(
        "CS-05",
        "Chinese Wall Breach — Information Leakage",
        ("agent-cs-001",),
        "High",
        "CRITICAL",
        ("SEC Section 15(g)", "FINRA Rule 5280", "MiFID II Article 16"),
        (
            DetectionSpec(
                "agent-cs-001",
                0.93,
                "CRITICAL",
                ("message_881", "barrier_event_005"),
                ("Investment_Banker", "Equity_Researcher"),
                "chinese_wall_breach",
                {
                    "message_phrase": "Don't cover TechCorp next week, trust me",
                    "report_delayed": True,
                },
            ),
        ),
        3,
        ("Internal investigation report", "SEC notification", "Deal team isolation protocol"),
    ),
    "CS-06": ScenarioSpec(
        "CS-06",
        "Wash Trading — Cross-Account Coordination",
        ("agent-tm-001",),
        "High",
        "HIGH",
        ("CEA Section 4c(a)", "SEC Rule 10b-5", "FINRA Rule 5210"),
        (
            DetectionSpec(
                "agent-tm-001",
                0.87,
                "HIGH",
                ("wash_trade_034", "circular_counterparty_002"),
                ("Account_A", "Account_B"),
                "wash_trading",
                {"matching_trades": 34, "price_tolerance_bps": 2, "alternating_sides": True},
            ),
        ),
        2,
        ("Exchange referral", "Internal trading desk review"),
    ),
    "CS-07": ScenarioSpec(
        "CS-07",
        "Regulatory Change Impact — New Margin Requirements",
        ("agent-ru-001",),
        "Medium",
        "MEDIUM",
        ("SEC Swap Margin Rule", "Basel III CRE54", "EMIR Margin Rules"),
        (
            DetectionSpec(
                "agent-ru-001",
                None,
                None,
                ("sec_final_rule_2026", "margin_methodology_impact"),
                ("swap_margin_rule_2026",),
                "regulatory_change",
                {
                    "initial_margin_increase_pct": 25,
                    "effective_days": 120,
                    "notional_affected_usd": 2100000000,
                    "counterparties": 340,
                    "days_to_comply": 45,
                },
            ),
        ),
        1,
        ("Impact assessment report", "Implementation timeline", "Stakeholder notification"),
        special_update=True,
        update_type="regulatory_change",
    ),
    "CS-08": ScenarioSpec(
        "CS-08",
        "Misleading Marketing — Performance Claims",
        ("agent-cs-001",),
        "Low-Medium",
        "CRITICAL",
        ("SEC Rule 206(4)-1", "FINRA Rule 2210", "FCA COBS 4"),
        (
            DetectionSpec(
                "agent-cs-001",
                0.96,
                "CRITICAL",
                ("marketing_claim_001", "stress_loss_analysis_001"),
                ("Structured_Product_X", "3400_prospects"),
                "misleading_marketing",
                {"claimed_return_pct": 12, "capital_loss_stress_pct": 40, "guaranteed_claim": True},
            ),
        ),
        3,
        ("Marketing withdrawal order", "Client correction notice", "Regulatory notification"),
    ),
    "CS-09": ScenarioSpec(
        "CS-09",
        "Sanctions Violation — Indirect Counterparty Exposure",
        ("agent-tm-001", "agent-ru-001"),
        "High",
        "CRITICAL",
        ("OFAC Regulations", "31 CFR Part 501", "EU Sanctions Regulation"),
        (
            DetectionSpec(
                "agent-tm-001",
                0.94,
                "CRITICAL",
                ("wire_intermediary_chain_003", "sdn_match_001"),
                ("Corporate_Client_7", "SDN_Subsidiary"),
                "sanctions_violation",
                {"intermediary_bank_count": 3, "sdn_added_hours_ago": 48},
            ),
            DetectionSpec(
                "agent-ru-001",
                0.98,
                "CRITICAL",
                ("ofac_update_048", "enhanced_screening_001"),
                ("SDN_Subsidiary",),
                "sanctions_violation",
                {"regulatory_update_confirmed": True, "sdn_added_hours_ago": 48},
            ),
        ),
        4,
        ("OFAC compliance report", "Transaction hold documentation", "Voluntary disclosure draft"),
    ),
    "CS-10": ScenarioSpec(
        "CS-10",
        "Front-Running — Client Order Anticipation",
        ("agent-tm-001",),
        "Medium",
        "CRITICAL",
        ("SEC Section 17(j)", "Investment Company Act Section 17(j)", "FINRA Rule 5270"),
        (
            DetectionSpec(
                "agent-tm-001",
                0.90,
                "CRITICAL",
                ("personal_trade_lead_089", "client_order_timing_010"),
                ("Trader_07",),
                "front_running",
                {
                    "profitable_trade_pct": 89,
                    "average_return_pct": 2.3,
                    "lead_time_minutes": "10-30",
                },
            ),
        ),
        3,
        ("Internal disciplinary report", "Client notification", "Regulatory referral"),
    ),
    "CS-11": ScenarioSpec(
        "CS-11",
        "Data Privacy Violation — Cross-Border Transfer",
        ("agent-cs-001", "agent-ru-001"),
        "Medium",
        "HIGH",
        ("GDPR Articles 44-49", "Schrems II"),
        (
            DetectionSpec(
                "agent-cs-001",
                0.87,
                "HIGH",
                ("transfer_14000_eu_001", "missing_scc_001"),
                ("EU_Residents_14000",),
                "data_privacy_violation",
                {
                    "transfer_to_non_adequate_jurisdiction": True,
                    "scc_documented": False,
                    "consent": False,
                },
            ),
            DetectionSpec(
                "agent-ru-001",
                0.95,
                "HIGH",
                ("schrems_ii_confirmation_001", "gdpr_article_44_001"),
                ("EU_Residents_14000",),
                "data_privacy_violation",
                {
                    "regulatory_confirmation": "GDPR Article 44 requires SCCs",
                    "privacy_shield_invalidated": True,
                },
            ),
        ),
        2,
        ("Data breach notification draft (GDPR Article 33)", "DPO assessment", "Remediation plan"),
    ),
    "CS-12": ScenarioSpec(
        "CS-12",
        "Concentration Risk — Portfolio Limit Breach",
        ("agent-tm-001",),
        "Low",
        "MEDIUM",
        ("Investment Company Act Section 13", "SEC Form N-PORT", "UCITS concentration limits"),
        (
            DetectionSpec(
                "agent-tm-001",
                0.75,
                "MEDIUM",
                ("sector_concentration_028", "limit_025_001"),
                ("Fund_12", "Sector_12"),
                "concentration_risk",
                {"concentration_pct": 28, "limit_pct": 25, "persistent_trading_days": 5},
            ),
        ),
        1,
        ("Prospectus deviation report", "Portfolio rebalancing recommendation"),
    ),
    "CS-13": ScenarioSpec(
        "CS-13",
        "Off-Channel Communication — Personal Device Usage",
        ("agent-cs-001",),
        "Medium",
        "HIGH",
        ("SEC Rule 17a-4", "FINRA Rule 3110", "FINRA Regulatory Notice 23-06"),
        (
            DetectionSpec(
                "agent-cs-001",
                0.90,
                "HIGH",
                ("whatsapp_reps_007", "recordkeeping_gap_007"),
                ("Registered_Representatives_7",),
                "off_channel_communication",
                {
                    "personal_device": "WhatsApp",
                    "representatives": 7,
                    "missing_official_channel_records": True,
                    "negative_signal": "low_official_channel_volume",
                },
            ),
        ),
        2,
        ("Record-keeping violation report", "Remediation plan", "Self-reporting recommendation"),
    ),
    "CS-14": ScenarioSpec(
        "CS-14",
        "Late Trading — Mutual Fund NAV Manipulation",
        ("agent-tm-001",),
        "Medium",
        "CRITICAL",
        ("SEC Rule 22c-1", "Investment Company Act Section 22(c)"),
        (
            DetectionSpec(
                "agent-tm-001",
                0.90,
                "CRITICAL",
                ("nav_timestamp_014", "late_entry_pattern_001"),
                ("Mutual_Fund_14",),
                "late_trading",
                {
                    "orders": 14,
                    "official_cutoff": "16:00:00 ET",
                    "system_entry_window": "16:12-16:23 ET",
                    "same_day_pricing": True,
                },
            ),
        ),
        3,
        ("SEC referral", "Fund board notification", "Client restitution calculation"),
    ),
    "CS-15": ScenarioSpec(
        "CS-15",
        "Best Execution Failure — Systematic Order Routing Bias",
        ("agent-tm-001",),
        "Medium",
        "HIGH",
        ("SEC Rule 606", "FINRA Rule 5310", "MiFID II Best Execution"),
        (
            DetectionSpec(
                "agent-tm-001",
                0.84,
                "HIGH",
                ("routing_bias_078", "venue_price_gap_015"),
                ("Equity_Order_Routing",),
                "best_execution_failure",
                {
                    "lookback_days": 90,
                    "single_venue_pct": 78,
                    "threshold_pct": 50,
                    "better_venues": 3,
                    "price_advantage_cents": "0.5-1.5",
                },
            ),
        ),
        2,
        ("Best execution analysis", "Venue comparison report", "Routing policy review"),
    ),
    "CS-16": ScenarioSpec(
        "CS-16",
        "Conflict of Interest — Research Independence",
        ("agent-cs-001", "agent-tm-001"),
        "High",
        "CRITICAL",
        ("SEC Regulation AC", "FINRA Rule 2241", "Global Research Settlement"),
        (
            DetectionSpec(
                "agent-cs-001",
                0.89,
                "CRITICAL",
                ("research_rating_change_001", "ib_meetings_002"),
                ("Research_Analyst",),
                "research_independence",
                {
                    "attributed_entity": "analyst_with_ib_pressure",
                    "rating_change": "sell_to_buy",
                    "days_before_offering": 3,
                    "ib_meetings": 2,
                },
            ),
            DetectionSpec(
                "agent-tm-001",
                0.83,
                "CRITICAL",
                ("pre_rating_volume_001", "unusual_options_002"),
                ("Research_Desk",),
                "research_independence",
                {
                    "attributed_entity": "broader_conspiracy",
                    "volume_increase_days_before": 2,
                    "unusual_options_activity": True,
                },
            ),
        ),
        3,
        ("Research independence violation", "Global Research Settlement compliance review"),
        use_conflict_resolver=True,
        expected_conflict_type="C",
    ),
    "CS-17": ScenarioSpec(
        "CS-17",
        "Elder Financial Exploitation",
        ("agent-tm-001", "agent-cs-001"),
        "High",
        "CRITICAL",
        ("FINRA Rules 2165 and 4512", "SEC Senior Safe Act"),
        (
            DetectionSpec(
                "agent-tm-001",
                0.87,
                "CRITICAL",
                ("elder_trade_spike_047", "poa_trade_instruction_001"),
                ("Client_84", "POA_Holder"),
                "elder_financial_exploitation",
                {
                    "client_age": 84,
                    "trades_in_month": 47,
                    "historical_monthly_average": 2,
                    "account_decline_pct": 22,
                    "poa_filed_weeks_ago": 6,
                },
            ),
            DetectionSpec(
                "agent-cs-001",
                0.85,
                "CRITICAL",
                ("coercive_language_001", "urgent_dont_tell_002"),
                ("Client_84", "POA_Holder"),
                "elder_financial_exploitation",
                {"coercive_language": True, "urgency_tactics": True, "isolation_tactics": True},
            ),
        ),
        3,
        (
            "Elder exploitation SAR",
            "Adult protective services notification",
            "POA revocation recommendation",
        ),
    ),
    "CS-18": ScenarioSpec(
        "CS-18",
        "FALSE POSITIVE — Legitimate Block Trade",
        ("agent-tm-001",),
        "Medium",
        "NO ALERT",
        ("N/A — negative test",),
        (
            DetectionSpec(
                "agent-tm-001",
                0.65,
                "MEDIUM",
                ("block_trade_initial_001",),
                ("Institutional_Client_18",),
                "unusual_volume",
                {
                    "block_trade_usd": 450000000,
                    "adv_pct": 8,
                    "initial_flag": True,
                    "pre_arranged": True,
                    "documentation_confirmed": True,
                    "disclosed_rebalancing": True,
                    "known_institutional_client": True,
                    "revised_confidence": 0.15,
                },
            ),
        ),
        None,
        ("No report generated — false-positive suppression record",),
        no_alert=True,
        special_update=True,
    ),
    "CS-19": ScenarioSpec(
        "CS-19",
        "Multi-Jurisdiction Regulatory Conflict",
        ("agent-ru-001",),
        "High",
        "HIGH",
        ("EMIR Reporting Obligation", "MAS Securities and Futures Act"),
        (
            DetectionSpec(
                "agent-ru-001",
                0.50,
                "HIGH",
                ("emir_one_day_reporting_001", "mas_cross_border_restriction_001"),
                ("EU_Clients_SG_Booked_Positions",),
                "regulatory_conflict",
                {
                    "confidence_methodology": "N/A: regulatory conflict",
                    "affected_jurisdictions": ["EU", "Singapore"],
                    "conflicting_regulations": ["EMIR", "MAS_SFA"],
                    "legal_counsel_required": True,
                },
            ),
        ),
        4,
        (
            "Regulatory conflict analysis",
            "Legal opinion request",
            "Jurisdictional compliance strategy",
        ),
        expected_conflict_type="E",
    ),
    "CS-20": ScenarioSpec(
        "CS-20",
        "COORDINATED SCENARIO — Complex Money Laundering through Trade Finance",
        ("agent-tm-001", "agent-cs-001", "agent-ru-001", "agent-rg-001"),
        "Very High",
        "CRITICAL",
        ("BSA/AML", "OFAC", "Trade-Based Money Laundering Red Flags", "FATF Recommendations"),
        (
            DetectionSpec(
                "agent-tm-001",
                0.90,
                "CRITICAL",
                tuple(f"cs20_tm_evidence_{i:02d}" for i in range(1, 7)),
                ("Trade_Client_20", "Beneficiary_20"),
                "trade_based_money_laundering",
                {"trade_mispricing_pct": 300, "intermediary_bank_count": 5, "layering": True},
            ),
            DetectionSpec(
                "agent-cs-001",
                0.91,
                "CRITICAL",
                tuple(f"cs20_cs_evidence_{i:02d}" for i in range(1, 7)),
                ("RM_20",),
                "trade_based_money_laundering",
                {
                    "override_count": 2,
                    "pressure_phrases": ["expedite this for VIP client", "override the hold"],
                    "rm_misconduct": True,
                },
            ),
            DetectionSpec(
                "agent-ru-001",
                0.93,
                "CRITICAL",
                tuple(f"cs20_ru_evidence_{i:02d}" for i in range(1, 7)),
                ("Beneficiary_20",),
                "trade_based_money_laundering",
                {
                    "fatf_update_days_ago": 14,
                    "enhanced_due_diligence": True,
                    "regulatory_update_confirmed": True,
                },
            ),
            DetectionSpec(
                "agent-rg-001",
                0.95,
                "CRITICAL",
                tuple(f"cs20_rg_evidence_{i:02d}" for i in range(1, 7)),
                ("Board_20",),
                "trade_based_money_laundering",
                {"board_level_reporting": True, "evidence_compilation": "20+ items"},
            ),
        ),
        4,
        (
            "SAR filing (FinCEN)",
            "Trade finance review report",
            "RM conduct investigation report",
            "Sanctions screening report",
            "Board-level executive summary",
        ),
    ),
}
