"""Synthetic scenario specifications for CS-01 through CS-10."""

from __future__ import annotations

from src.mcms.scenario_support import DetectionSpec, ScenarioSpec

SCENARIOS: dict[str, ScenarioSpec] = {
    "CS-01": ScenarioSpec(
        "CS-01",
        "Insider Trading — Pre-Announcement Accumulation",
        ("agent-tm-001", "agent-cs-001"),
        "High",
        "CRITICAL",
        ("SEC Rule 10b-5", "FINRA Rule 2010", "Insider Trading Sanctions Act"),
        (
            DetectionSpec(
                "agent-tm-001",
                0.79,
                "CRITICAL",
                ("trade_pattern_001", "volume_anomaly_002"),
                ("PM_John_Doe", "Account_44521"),
                "insider_trading",
                {
                    "position_above_90_day_average_pct": 340,
                    "buy_orders_clustered_before_close": True,
                },
            ),
            DetectionSpec(
                "agent-cs-001",
                0.90,
                "CRITICAL",
                ("email_4452", "calendar_entry_892"),
                ("PM_John_Doe", "CFO_CompanyX"),
                "insider_trading",
                {"private_dinner": True, "official_channel_follow_up": False},
            ),
        ),
        3,
        (
            "SAR filing draft (FinCEN Form 111)",
            "Internal investigation report",
            "Regulatory notification draft (SEC)",
        ),
        expected_conflict_type=None,
    ),
    "CS-02": ScenarioSpec(
        "CS-02",
        "Market Manipulation — Spoofing in Futures Markets",
        ("agent-tm-001",),
        "Medium",
        "HIGH",
        ("Dodd-Frank Act Section 747", "CEA Section 4c(a)(5)", "CME Rule 575"),
        (
            DetectionSpec(
                "agent-tm-001",
                0.88,
                "HIGH",
                ("spoofing_signature_001", "cancel_burst_047"),
                ("crude_oil_desk",),
                "spoofing",
                {
                    "repetitions": 47,
                    "cancel_latency_ms": "200-500",
                    "opposite_side_execution": True,
                },
            ),
        ),
        2,
        ("CFTC referral draft", "Internal surveillance report"),
    ),
    "CS-03": ScenarioSpec(
        "CS-03",
        "Unsuitable Investment Recommendation",
        ("agent-cs-001", "agent-tm-001"),
        "High",
        "HIGH",
        ("FINRA Rule 2111", "SEC Regulation Best Interest"),
        (
            DetectionSpec(
                "agent-cs-001",
                0.89,
                "HIGH",
                ("advisor_message_001", "ips_violation_012"),
                ("Advisor_12",),
                "unsuitable_recommendation",
                {"retirement_clients": 12, "client_age_range": "68-82", "leveraged_etf": True},
            ),
            DetectionSpec(
                "agent-tm-001",
                0.75,
                "MEDIUM",
                ("trade_confirmations_012", "aum_risk_002"),
                ("Advisor_12",),
                "unsuitable_recommendation",
                {"aum_at_risk_usd": 2300000, "clients_executed": 12},
            ),
        ),
        2,
        ("FINRA referral", "Client remediation plan", "Advisor disciplinary report"),
        use_conflict_resolver=True,
        expected_conflict_type="B",
    ),
    "CS-04": ScenarioSpec(
        "CS-04",
        "AML — Structuring Deposits",
        ("agent-tm-001",),
        "Medium",
        "CRITICAL",
        ("Bank Secrecy Act", "31 CFR 1020.320", "FinCEN SAR"),
        (
            DetectionSpec(
                "agent-tm-001",
                0.95,
                "CRITICAL",
                ("structuring_pattern_023", "branch_spread_007"),
                ("Depositor_004",),
                "aml_structuring",
                {
                    "deposit_count": 23,
                    "branch_count": 7,
                    "total_usd": 214000,
                    "amount_range_usd": "8500-9900",
                },
            ),
        ),
        3,
        ("SAR draft (FinCEN Form 111)", "Branch alert notification"),
    ),
    "CS-05": ScenarioSpec(
        "CS-05",
        "Chinese Wall Breach — Information Leakage",
        ("agent-cs-001",),
        "High",
        "CRITICAL",
        ("SEC Section 15(g)", "FINRA Rule 5280", "MiFID II Article 16"),
        (
            DetectionSpec(
                "agent-cs-001",
                0.93,
                "CRITICAL",
                ("message_881", "barrier_event_005"),
                ("Investment_Banker", "Equity_Researcher"),
                "chinese_wall_breach",
                {
                    "message_phrase": "Don't cover TechCorp next week, trust me",
                    "report_delayed": True,
                },
            ),
        ),
        3,
        ("Internal investigation report", "SEC notification", "Deal team isolation protocol"),
    ),
    "CS-06": ScenarioSpec(
        "CS-06",
        "Wash Trading — Cross-Account Coordination",
        ("agent-tm-001",),
        "High",
        "HIGH",
        ("CEA Section 4c(a)", "SEC Rule 10b-5", "FINRA Rule 5210"),
        (
            DetectionSpec(
                "agent-tm-001",
                0.87,
                "HIGH",
                ("wash_trade_034", "circular_counterparty_002"),
                ("Account_A", "Account_B"),
                "wash_trading",
                {"matching_trades": 34, "price_tolerance_bps": 2, "alternating_sides": True},
            ),
        ),
        2,
        ("Exchange referral", "Internal trading desk review"),
    ),
    "CS-07": ScenarioSpec(
        "CS-07",
        "Regulatory Change Impact — New Margin Requirements",
        ("agent-ru-001",),
        "Medium",
        "MEDIUM",
        ("SEC Swap Margin Rule", "Basel III CRE54", "EMIR Margin Rules"),
        (
            DetectionSpec(
                "agent-ru-001",
                None,
                None,
                ("sec_final_rule_2026", "margin_methodology_impact"),
                ("swap_margin_rule_2026",),
                "regulatory_change",
                {
                    "initial_margin_increase_pct": 25,
                    "effective_days": 120,
                    "notional_affected_usd": 2100000000,
                    "counterparties": 340,
                    "days_to_comply": 45,
                },
            ),
        ),
        1,
        ("Impact assessment report", "Implementation timeline", "Stakeholder notification"),
        special_update=True,
        update_type="regulatory_change",
    ),
    "CS-08": ScenarioSpec(
        "CS-08",
        "Misleading Marketing — Performance Claims",
        ("agent-cs-001",),
        "Low-Medium",
        "CRITICAL",
        ("SEC Rule 206(4)-1", "FINRA Rule 2210", "FCA COBS 4"),
        (
            DetectionSpec(
                "agent-cs-001",
                0.96,
                "CRITICAL",
                ("marketing_claim_001", "stress_loss_analysis_001"),
                ("Structured_Product_X", "3400_prospects"),
                "misleading_marketing",
                {"claimed_return_pct": 12, "capital_loss_stress_pct": 40, "guaranteed_claim": True},
            ),
        ),
        3,
        ("Marketing withdrawal order", "Client correction notice", "Regulatory notification"),
    ),
    "CS-09": ScenarioSpec(
        "CS-09",
        "Sanctions Violation — Indirect Counterparty Exposure",
        ("agent-tm-001", "agent-ru-001"),
        "High",
        "CRITICAL",
        ("OFAC Regulations", "31 CFR Part 501", "EU Sanctions Regulation"),
        (
            DetectionSpec(
                "agent-tm-001",
                0.94,
                "CRITICAL",
                ("wire_intermediary_chain_003", "sdn_match_001"),
                ("Corporate_Client_7", "SDN_Subsidiary"),
                "sanctions_violation",
                {"intermediary_bank_count": 3, "sdn_added_hours_ago": 48},
            ),
            DetectionSpec(
                "agent-ru-001",
                0.98,
                "CRITICAL",
                ("ofac_update_048", "enhanced_screening_001"),
                ("SDN_Subsidiary",),
                "sanctions_violation",
                {"regulatory_update_confirmed": True, "sdn_added_hours_ago": 48},
            ),
        ),
        4,
        ("OFAC compliance report", "Transaction hold documentation", "Voluntary disclosure draft"),
    ),
    "CS-10": ScenarioSpec(
        "CS-10",
        "Front-Running — Client Order Anticipation",
        ("agent-tm-001",),
        "Medium",
        "CRITICAL",
        ("SEC Section 17(j)", "Investment Company Act Section 17(j)", "FINRA Rule 5270"),
        (
            DetectionSpec(
                "agent-tm-001",
                0.90,
                "CRITICAL",
                ("personal_trade_lead_089", "client_order_timing_010"),
                ("Trader_07",),
                "front_running",
                {
                    "profitable_trade_pct": 89,
                    "average_return_pct": 2.3,
                    "lead_time_minutes": "10-30",
                },
            ),
        ),
        3,
        ("Internal disciplinary report", "Client notification", "Regulatory referral"),
    ),
}
